name: gate_guard
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  google_sign_in: ^6.2.1
  firebase_auth: ^5.1.4
  http: ^1.2.2
  shared_preferences: ^2.0.13
  timeago: ^3.0.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  badges: ^3.1.2
  dropdown_button2: ^2.3.9
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  image_picker: ^1.1.2
  image: ^4.3.0
  flutter_otp_text_field: ^1.2.0
  pin_code_fields: ^8.0.1
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  intl: ^0.19.0
  share_plus: ^10.1.1
  screenshot: ^3.0.0
  url_launcher: ^6.0.20
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
    - assets/app_logo/
    - assets/images/cab/
    - assets/images/delivery/
    - assets/images/guest/
    - assets/images/other/
    - assets/animations/

  uses-material-design: true
